### ISSUE TITLE
Remove Gavin Williamson Template from website

### ISSUE THREAD

**Issue by davidswarbrick** [puria-radmard/emaildrafter#7]
The template email to the secretary of state for education should not be included as the automatic reply clearly states that requests about work for the DofE need to be submitted via their webform.

In the future, we may be able to implement submitting the form remotely from our site, but for now we should remove the template as it is not helping & taking up time + space on the site.

**Comment by behradkoohy** [comment]
fixed on branch 'remove_gavin'. will merge into master
